/*
General Transaction
-Backing up the database
-Help menu
*/
/*
General Restrictions
-Access control
-Employee can keep record of order from a user
-Group information should be kept private to that group
-Group owner's approval is needed to join a group
-User's consent is needed to be joined to a group
*/


/*
User-level Transactions
-Register
-Sign in and out
-Post message in personal pages
-Send/Receive/Delete message

-Create/Delete/Rename group
-Search/Add/Remove user to group
-Create/Remove/Like/Unlike/Modify post
-Create/Like/Remove/Unlike/Modify comment

-Join/Unjoin group
-Create/Remove/Like/Unlike/Modify post on group page
-Create/Remove/Like/Unlike/Modify comment on group page

-Purchase one or more copies of an advertised item

-Retrieve customer's current groups
-Customer's account history
-Best-seller list of items
-Personalized item suggestion list
*/
CREATE TABLE UserData (
	id int(11) NOT NULL AUTO_INCREMENT,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	address varchar(95) NOT NULL,
	city varchar(35) NOT NULL,
	state char(2) NOT NULL,
	zipcode varchar(10) NOT NULL, 
	telephone varchar(12) NOT NULL,
	email varchar(255) NOT NULL,
	account_number varchar(12) NOT NULL,
	account_created date NOT NULL,
	creditcard varchar(16) NOT NULL, --keep account history
	preference --advertisements
	rating --active status in terms of making purchases
	--Can connect with other users
	--Can post message on page
	--Can follow up on Wall
	--Can like or comment on post
	--Can create group
	--Can make purchase
)

CREATE TABLE Group (
	GroupId
	GroupName
	Type
	Owner
)

CREATE TABLE Pages (
	PageId
	Owner
	Group
	PostCount
)

CREATE TABLE Comments (
	CommentId
	Date
	Content
	Author
)

CREATE TABLE Messages (
	MessageId
	Date
	Subject
	Content
	Sender
	Receiver
)

CREATE TABLE Advertisement (
	AdId
	EmployeeId
	Type --(e.g. clothing, computers)
	Date
	Company --(e.g. Ford, Gap, Google)
	ItemName --(e.g. particular car, article of clothing, smartphone)
	Content
	UnitPrice
	NumUnit
)

CREATE TABLE Sales (
	TransactionId
	Date
	AdId
	NumUnit
	AccNum
)
/*
Manager-Level Transactions
-Add/Edit/Delete employee information
-Sales report for a particular month
-Listing of all items advertised on the site
-Listing of transactions by item name or user name
-Listing of revenue generated by item, item type, customer
-Determine which employee generated most revenue
-Determine which customer generated most revenue
-Listing of most active items
-Listing of customer who purchased a particular item
-Listing of all items for a given company

-Add/Delete users
*/
/*
Customer-Representative Transaction
-Create/Delete advertisement
-Record a transaction
-Add/Edit/Delete information for a customer
-Produce customer mailing list
-Produce a list of item suggestion for a given customer
*/
CREATE TABLE Employee (
	SSN
	LastName
	FirstName
	Address
	City
	State
	ZipCode
	Tel
	StartDate
	HourlyRate
)