<%-- 
    Document   : representative_home
    Created on : Nov 19, 2016, 7:33:31 PM
    Author     : bryan
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="../resources/css/manager.css" rel="stylesheet" type="text/css">
        <title>Customer Representative & Manager Menu</title>
    </head>
    <body>
        <% if (session.getAttribute("ismanager") != null) { %>
        
        <jsp:include page="header.jsp"/>
        

                <h2>Customer Representative Actions:</h2>
            <ul><li><a href="advertisement.jsp">Create or Edit an Advertisement *TODO*</a></li>
                <li><a href="transaction.jsp">Record a Transaction *TODO*</a></li>
                <li><a href="users.jsp">Create or Edit User Information *TODO*</a></li>
                <li><a href="mailing_list.jsp">Produce Customer Mailing List</a></li>
                <li><a href="item_suggestions.jsp">Get Personalized Item Suggestions for a User</a></li>
                <li><a href="user_groups.jsp">Get Current Groups for a User</a></li>
                <li><a href="account_history.jsp">Get Account History for an Account</a></li>
                <li><a href="best_sellers.jsp">Get Best-Seller Item List</a></li></ul>
            <% if (session.getAttribute("ismanager") != null) {
                        if ((Boolean) session.getAttribute("ismanager")) { %>
                        <br />
                        <h2>Manager Actions:</h2>
                        <ul><li><a href="employee.jsp">Add or Edit Employee Information *TODO*</a></li>
                        <li><a href="sales_report.jsp">Obtain a Sales Report for a Particular Month *TODO*</a></li>
                        <li><a href="advertisement_list.jsp">View List of Advertisements *TODO*</a></li>
                        <li><a href="trans_list_item.jsp">View All Transactions by Item Name *TODO*</a></li>
                        <li><a href="trans_list_user.jsp">View All Transactions by User Name *TODO*</a></li>
                        <li><a href="revenue_item.jsp">View All Revenue Generated by Item *TODO*</a></li>
                        <li><a href="revenue_type.jsp">View All Revenue Generated by Item Type *TODO*</a></li>
                        <li><a href="revenue_customer.jsp">View All Revenue Generated by Customer *TODO*</a></li>
                        <li><a href="best_representative.jsp">Determine Which Representative Generated the Most Revenue *TODO*</a></li>
                        <li><a href="best_customer.jsp">Determine Which Customer Generated the Most Revenue *TODO*</a></li>
                        <li><a href="active_items.jsp">View Most Active Items *TODO*</a></li>
                        <li><a href="buyer_list.jsp">View All Customers Who Have Purchased an Item *TODO*</a></li>
                        <li><a href="company_item_list.jsp"View All Items for a Company *TODO*</a></li></ul>
                    <% }}; %>
        <% } else { %>
            <div id="error">Please <a href="representative_login.jsp">login</a> to access this page.</div>
        <% }; %>
    </body>
</html>
